### ISSUE TITLE
идеи+вопрос

### ISSUE THREAD

**Issue by amketamin** [Fequme/Economy-bot-discord-v2#3]
добавляй requements к ботам пж

+почему то не работает профиль(дает ошибки отрисовки картинок)

**Comment by zakatik1337** [comment]
Там код сломан, походу, я его вообще запустить не смог, всё перепробовал, так и не запустился.

**Comment by amketamin** [comment]
я запустить смог но  половина функций не работает

**Comment by Fequme** [comment]
окей, буду добавлять requements'ы к ботам

**Comment by Fequme** [comment]
не работать может из за того что не заполнен конфиг или не поменял айди в когах, у меня всё стабильно работает. Возможно ошибка отрисовки из за того что Pillow обновился и что-либо поменялось, попробуй поставить версию меньше

**Comment by amketamin** [comment]
> не работать может из за того что не заполнен конфиг или не поменял айди в когах, у меня всё стабильно работает. Возможно ошибка отрисовки из за того что Pillow обновился и что-либо поменялось, попробуй поставить версию меньше

Пробовал, и 9.5.0, и ластовую 10 с чем-то. При 10 - ошибка 9.5.0 - при использовании любой команды с Pillow - просто офается бот

**Comment by amketamin** [comment]
> не работать может из за того что не заполнен конфиг или не поменял айди в когах, у меня всё стабильно работает. Возможно ошибка отрисовки из за того что Pillow обновился и что-либо поменялось, попробуй поставить версию меньше

А про какие ID идет речь? ничего не нашел чета

**Comment by Fequme** [comment]
> > не работать может из за того что не заполнен конфиг или не поменял айди в когах, у меня всё стабильно работает. Возможно ошибка отрисовки из за того что Pillow обновился и что-либо поменялось, попробуй поставить версию меньше
> 
> А про какие ID идет речь? ничего не нашел чета

те же эмодзи, они уже не работают, их тоже нужно менять 
![image](https://github.com/Fequme/Economy-bot-discord-v2/assets/142742415/1a9fb3d7-2a52-46a2-819d-60dedcc853c1)

**Comment by Fequme** [comment]
или вот пример ID в коге кланов 
![image](https://github.com/Fequme/Economy-bot-discord-v2/assets/142742415/d5ae7d3e-9583-410b-9e55-e5a2cd039c3e)

**Comment by Fequme** [comment]
> > не работать может из за того что не заполнен конфиг или не поменял айди в когах, у меня всё стабильно работает. Возможно ошибка отрисовки из за того что Pillow обновился и что-либо поменялось, попробуй поставить версию меньше
> 
> Пробовал, и 9.5.0, и ластовую 10 с чем-то. При 10 - ошибка 9.5.0 - при использовании любой команды с Pillow - просто офается бот

запусти бота в консоли , а не через батник и посмотри ошибку
